### ISSUE TITLE
Losing all listeners when executing notific8

### ISSUE THREAD

**Issue by Lydnasty** [ralivue/notific8#67]
When executing notific8 for the first time, it creates divs for notifications, but at the same time looks like it replace all body html code and that removes all listeners defined.

**For example if I define:**
    $(document).ready(function(){
       $("#example").click(function(){
           console.log("!!");
       }) ;
    });

And then i execute notific8 function, this listener stops working.

I know i can defined it with .on() and it will probably work, but that's not the problem, i'm using angular and i lose all ng-click events -_-"
I think you should change the way you append divs to html code or force users to defined a div with an especific id / class and create all the magic inside that div.

Thanks for all

**Comment by zxpan** [comment]
I had the same issue

**Comment by willsteinmetz** [comment]
I just double-checked the source code to be sure and it definitely does not replace all of the HTML body code. If it did that, the demo wouldn't work at all because it would wipe out the form. If you look on [line 351](https://github.com/ralivue/notific8/blob/3.6.0/dist/notific8.js#L351) of the compiled, unminified JavaScript file in version 3.6.0, you can see the code where it is doing `body.innerHTML += ...` which is appending the containers. I can try setting the value generated for the container strings to a variable before appending it to see if that helps but all of the replace functions should be operating on the value being appended before it is appended so it should be the result of that chain that is getting appended to the body tag's HTML content.

What version of Angular are you using? I'm only familiar with 1.x so I can give that a try sometime next week when I have some time available.

Also, are you trying to add event handlers with jqLite? If so, you really ought to look into the built in directives for events like ng-click and such.

**Comment by willsteinmetz** [comment]
I tested the update in version 3.6.1 out using Angular 1.5.7. I created a component that just put a button on the page with an `ng-click` attribute that called a function which would open a new notification. With the update, I could click the button ad nauseam and continually get new notifications.
